### ISSUE TITLE
widget_title filter conflict

### ISSUE THREAD

**Issue by FriendlyWP** [Daronspence/acf-widgets#13] opened 2015-03-23 14:15 UTC
I use the following function fairly frequently to allow my clients to enter widget titles which will appear in the control panel, but not on the front end of the web site. This allows them to distinguish between 10 versions of a specific widget type (text widgets, for instance) in the Appearance > Widgets control panel, without having all those titles appear on the site. Titles that begin with an ! exclamation point won't show on the front end. 

All the function does is look to see if a widget title starts with an exclamation point (!), and if it does, return blank when rendered on the front end. 

```
add_filter( 'widget_title', 'remove_widget_title');
function remove_widget_title( $widget_title ) {
    if ( substr ( $widget_title, 0, 1 ) == '!' )
        return;
    else 
        return ( $widget_title );
}
```

I've never had a problem with it working in any other widget, but for ACF Widgets it returns empty in the control panel as well as the front end of the site if the title begins with an exclamation point. I've tried various low/high priorities and none seem to help. 

Obviously not a biggie, and if you choose not to change the code I understand, but I figured I'd share since the function's never exhibited this behavior before on any native or plugin-added widgets. 

Cheers!

**Comment by daronspence** [comment] 2015-03-23 17:59
I think I know what the Issue is here. I'm applying the 'widget-title' filters on the backend as well, which I would like to keep, I think... WP core does it...I'll check and get back to you.

**Comment by daronspence** [comment] 2015-03-25 00:27
This should be fixed now in the latest commit. I think I'm going to be pushing out 1.4 here pretty soon. I got one other beta tester who has had good things to say and he's running some major (millions of pageviews) sites with the plugin installed and all is well.

**Closed as completed by daronspence** 2015-03-25 00:27 UTC
